### ISSUE TITLE
Drop support of officialy unsupported PHP versions

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-client-php#104]
- [x] 5.3

**Comment by redox** [comment]
I thought we wanted to keep that for Wordpress where 21% of the users are still running 5.3, did I miss something?

**Comment by JanPetr** [comment]
We discussed with guys that in 2.0 major we will drop support of 5.3. I will check with @rayrutjes how he plans to handle WP.

**Comment by JanPetr** [comment]
So we will not drop PHP 5.3 support until we release new WP plugin and have relevant data about PHP versions used on WP instances. 

I'm closing the issue now.
