### ISSUE TITLE
Check for JSON errors after json_encode() as well as json_decode()

### ISSUE THREAD

**Issue by longwave** [algolia/algoliasearch-client-php#113]
If you attempt to send malformed UTF-8 to Algolia you get 400 Bad Request as the HTTP response, this is because `json_encode()` fails earlier and sends an empty string instead of the correct JSON packet.

There is already a sanity check for the returned JSON, it would be good to add a similar sanity check before attempting to send any JSON to make this situation easier to debug.

**Comment by rayrutjes** [comment]
You are right @longwave . Feel free to start a PR. Otherwise we will tackle this ASAP.

Thx for the issue!
