### ISSUE TITLE
Little Concat-Typo

### ISSUE THREAD

**Issue by synonymous1984** [algolia/algoliasearch-client-php#182]
Hi there,

You´ve a small concatenation typo in the client class:
https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L917

Should be
```
throw new AlgoliaException(isset($answer['message']) ? $answer['message'] : $http_status . ' error');
````
instead of
```
throw new AlgoliaException(isset($answer['message']) ? $answer['message'] : $http_status + ' error');
```

**Comment by rayrutjes** [comment]
Indeed, thanks for spotting that! Will fix ASAP

**Comment by rayrutjes** [comment]
Merged 🎉 

Thanks @synonymous1984 ;)

**Comment by synonymous1984** [comment]
You are welcome :) @rayrutjes
