### ISSUE TITLE
Hosts unreachable

### ISSUE THREAD

**Issue by jagroop** [algolia/algoliasearch-client-php#257]
Hi am getting this host's unreachable exception

```
Hosts unreachable: Operation timed out after 1089 milliseconds with 0 out of 0 bytes received,Operation timed out after 1002 milliseconds with 0 out of 0 bytes received,Resolving timed out after 3000 milliseconds,Operation timed out after 3033 milliseconds with 0 out of 0 bytes received
```

if this an issue related to request timeout then how can I increase request timeout.

Thanks

**Comment by rayrutjes** [comment]
Hi @jagroop ,

In general we don't recommend raising the connection timeout.
In your case it seems that the network is not available because even with the timeouts set to 3s you still don't manage to establish the connection.

Can you make sure your server is able to reach the outside?

**Comment by jagroop** [comment]
Hi @rayrutjes 
Hmm yes you are right .  i just checked it and its working fine on Production server.  :+1:  It could be a network problem.

Anyhow in case if i just want to increase the time out on dev server only how can i do that ?

 thanks for the help :)

**Comment by rayrutjes** [comment]
I doubt that increasing the timeout will fix your problem given that one of the attempt already raised the timeout as high as 3s. This is part of the built in re-try strategy.

If you insist, you can call `$client->setConnectTimeout(30);` ;)

I'm closing this for but feel free to share the solution if any for your specific local environment.
