### ISSUE TITLE
Version class perform useless file_get_contents for all requests

### ISSUE THREAD

**Issue by damienalexandre** [algolia/algoliasearch-client-php#26]
I think all this code in **Version.php** could be replaced by a simple **const**:

```php
  public static function getValue() {
    if (!isset(self::$value)) {
      $vpath = dirname(__FILE__) . "/../../composer.json";
      if (file_exists($vpath)) {
        $composerJson = file_get_contents($vpath);
        if ($composerJson != false) {
          $composer = json_decode($composerJson);
          if ($composer != null) {
            self::$value = $composer->version;
            return self::$value;
          }
        }
      }
      self::$value = "N/A";
    } else {
      return self::$value;
    }
  }
```

Because:

- you do not need a "version" key in the composer.json file, you already use git tags and composer/packagist read them;
- this will perform disk access each time we use the client, which is bad for performances;
- a PHP constant will be better for users not using Composer;

All you have to do is to update the const when you tag a new version instead of updating the composer file.

So, new Version.php:

```php
namespace AlgoliaSearch;

class Version {
    const NUMBER = '1.5.2';
}
```

I can send the pull request if you agree with my statements.

**Comment by redox** [comment]
Hey @damienalexandre,

the idea was to update the code in a single/unique place to bump the version. I think we chose to store it in the `composer.json` by default but if it's not a best-practice and if you confirm that it's useless to have it in the `composer.json` file, feel free to submit the PR; we'll be happy to merge!
