### ISSUE TITLE
searchDisjunctiveFaceting is using `facetFilters` instead of `filters`

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-php#277]
Not sure if it's a bug or not.
See: https://github.com/algolia/algoliasearch-client-php/blob/0b8269e1fb9b63bac2a127c53803a64ca7c85b00/src/AlgoliaSearch/Index.php#L741

**Comment by rayrutjes** [comment]
Thanks for reporting that one @ElPicador 
This method is deprecated, and you should use the search instead:

`$index->search($query, ['disjunctiveFacets' => $disjunctive_facets]]);`

**Comment by ElPicador** [comment]
Yep, sorry. Closing it.
