### ISSUE TITLE
Query multiple indices in PHP?

### ISSUE THREAD

**Issue by damienalexandre** [algolia/algoliasearch-client-php#28]
Hi there, not sure this is the right place to ask this,
the PHP documentation display a [Query multiple indices](https://www.algolia.com/doc/php#MultiQuery) part but examples are written in Javascript.

It looks like the PHP client does not support this interface? (there is "batch" for writing, not for reading)

I didn't look at the JavaScript implementation yet, but either ways:
- if this an API method, we could simply add it;
- if this use two concurrent HTTP calls, this can be [done in PHP too](http://php.net/manual/en/function.curl-multi-init.php).

Thx,
Damien

**Comment by speedblue** [comment]
Hi Damien,

The PHP client support it but you are right the documentation is not clear. You can use the multipleQueries call on the index class. The prototype take an array of objects, each object describe the query ("query" key is for the query string and "indexName" key is for index name).

Julien

**Comment by damienalexandre** [comment]
Ok my bad, didn't see the *multipleQueries* method as I was looking called like the JS one's (addQueryInBatch, startQueriesBatch...).

Thanks for your time,
Damien
