### ISSUE TITLE
partialUpdateObject() Deletes old values when used

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-client-php#281]
I am uploading a few items into Algolia and later I update a few values using this function:
```
public function partialUpdateObject($partialObject, $createIfNotExists = true)
    {
        $queryString = $createIfNotExists ? '' : '?createIfNotExists=false';
        return $this->client->request(
            $this->context,
            'POST',
            '/1/indexes/'.$this->urlIndexName.'/'.urlencode($partialObject['objectID']).'/partial'.$queryString,
            array(),
            $partialObject,
            $this->context->writeHostsArray,
            $this->context->connectTimeout,
            $this->context->readTimeout
        );
    }
```
The first few times it works, but later when I use the update record I can se that I deletes other values in my record.
Eg:

When I first uploaded a record I had a value called **thumbnail** which contained a url.
When I later used the `partialUpdateObject()` to update a value called **title** the **thumbnail** value got removed from my record.

So how do I update certain values without removing other values? Lets say that I only want to update the **title** value of my record and nothing else

**Comment by rayrutjes** [comment]
Closing this one in favor of: https://discourse.algolia.com/t/partialupdateobject-deletes-old-values-when-used/933
