### ISSUE TITLE
\AlgoliaSearch\Index::__call should throw an exception on unhandled methods

### ISSUE THREAD

**Issue by longwave** [algolia/algoliasearch-client-php#285]
We just had to track down a silent failure bug where we were calling an invalid method on an index object, but not seeing any errors. This is because the `__call` implementation simply returns NULL if the method name is not recognised; only `browse` is actually handled by this method.

It would be good if an exception was thrown here to avoid others running into the same problem.

**Comment by rayrutjes** [comment]
Thanks for reporting this @longwave .

I just submitted a PR and will wait for the team mates to approve it ;)

Cheers!

**Comment by longwave** [comment]
Honestly amazed at the speed of response here, thank you!
