### ISSUE TITLE
Question: how to search with facet ?

### ISSUE THREAD

**Issue by chrisvidal** [algolia/algoliasearch-client-php#287]
Hi,

I would like to search in a index using a search query and also facet.
What is the best practices please ?
Any code example ?
Thank you

**Comment by rayrutjes** [comment]
Hi @chrisvidal ,

What we recommend, is that you do the searching in the frontend.
This will make sure the search is as fast as possible for your end users.

To do the implementation you can use UI libraries such as [InstantSearch](https://community.algolia.com/instantsearch.js/), or even the [Javascript API Client](https://github.com/algolia/algoliasearch-client-javascript).

You can find code samples & demos in each of those UI library docs. Here for InstantSearch for example: https://community.algolia.com/instantsearch.js/examples/

You can also checkout the docs of the JS Client here: https://www.algolia.com/doc/api-client/javascript/search/

**Comment by chrisvidal** [comment]
thks @rayrutjes 

but my use case is that i am creating an notification email containing result of saved searches by my user, hence i am using the algolia Laravel PHP client for.

**Comment by rayrutjes** [comment]
That makes sense @chrisvidal.
You can use the `filters` option.

Here are examples: https://www.algolia.com/doc/api-client/php/parameters/filters/

Here is an example:
```php
<?php
$results = $index->search(
    'your query string',
    [
        'filters' => 'category:Book'
    ]
);
```

**Comment by chrisvidal** [comment]
awesome ! thks @rayrutjes 
So i started to implemented this filters and i am facing this algolia error:

````php
[2017-04-28 21:49:49] dev.INFO: (updated_at>=1493386728 AND updated_at<=1493308800) AND ((categories:"Access Floor Contractors" OR categories:"Acoustical Contractors") AND (certifications:"BizSAFE")) 
````

````cmd
 [2017-04-28 21:49:49] dev.ERROR: exception 'AlgoliaSearch\AlgoliaException' with message 'filters: filter (X AND Y) OR Z is not allowed, only (X OR Y) AND Z 
````

**Comment by chrisvidal** [comment]
ok I fixed it, it does not like to double parenthesis
so this is working
````
(updated_at>=1493386728 AND updated_at<=1493308800) AND (categories:"Access Floor Contractors" OR categories:"Acoustical Contractors") AND (certifications:"BizSAFE") 
````

**Comment by chrisvidal** [comment]
Hmmm I am facing a weird behavior with facet search:
````
$results = $index->search('query', [
  'filters' => '(category:"Long Book title with space" OR category:Ebook)'
]);
````

does not work, the category:"Long Book title with space" is not found.
How we need to specify such a facet value ?

**Comment by JanPetr** [comment]
Hello @chrisvidal,

I'm sorry for the late answer. I just tested this filter:

```php
$results = $index->search('', [
    'filters' => '(categories.level1:"Men /// Blazers" OR categories.level1:"Home & Decor /// Decorative Accents")'
]);
```

and it works just fine. It should be just find to you double parentheses around a long titles. Did you make it work or do you still experience issues?

**Comment by julienbourdeau** [comment]
@chrisvidal I assumed your issue was fixed. Please let me know if you need further help, I'll reopen this issue.
