### ISSUE TITLE
forwardToReplicas not working

### ISSUE THREAD

**Issue by tillkruss** [algolia/algoliasearch-client-php#299]
I've set `$forwardToReplicas` to `true`, but the replicas don't inherit `searchableAttributes` or `attributesForFaceting`. Is there something I'm missing?

```php
$algolia->initIndex('products')->setSettings([
    'replicas' => [
        'products_popular',
        'products_newest',
    ],
    'ranking' => [
        'desc(trend)',
        'typo',
        'words',
        'filters',
        'proximity',
        'attribute',
        'exact',
        'custom',
    ],
    'searchableAttributes' => [
        'title,slug',
        'unordered(description)',
    ],
], true);
```

**Comment by rayrutjes** [comment]
Hey @tillkruss ,

In general, you would create your primary index without forwarding.
This would create the replicas with the settings of the primary index (even without forward to replicas).

Then you would push only the things that are common to your primary index and your replicas.

Could you be more specific about what you are trying to achieve?

**Comment by tillkruss** [comment]
I'm creating 3 indices that have 50+ lines of settings, I'm just trying to keep the code short.

I tried removing the `$forwardToReplicas` flag, same result. Some settings are forwarded to the replicas, for example `ranking`, but `searchableAttributes` and `attributesForFaceting` are not forwarded.

Is that an issue with Algolia, or with this SDK?

**Comment by tillkruss** [comment]
Turns out I need to first create the index, and then set the settings separately.
