### ISSUE TITLE
Weird handling of addApiKey parameters

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-client-php#301]
https://github.com/algolia/algoliasearch-client-php/blob/b0a1fc1e3efc54fde10cdfb0b83e20fc3cd4cfc5/src/AlgoliaSearch/Index.php#L1126-L1129

We are doing a weird thing.

We should not overwrite `validity`, `maxHitsPerQuery ` and `maxQueriesPerIPPerHour ` if they are already in `$params`

**Comment by rayrutjes** [comment]
Agreed, but I don't think we can do it while keeping backward compatibility.

**Comment by julienbourdeau** [comment]
This was fixed by https://github.com/algolia/algoliasearch-client-php/pull/357

I think BC here is okay, the feature never worked so it probably wasn't used. If you set validity in the `$obj` it wasn't taken into account.
