### ISSUE TITLE
[Improvements] Tag @return is missing in PhpDoc blocks

### ISSUE THREAD

**Issue by b-viguier** [algolia/algoliasearch-client-php#32]
All functions are well documented for input parameters, thanks to the [`@param` tag](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/param.html) , but the [`@return` tag](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html) is never used to document the return type.

This information is very useful for some IDE (like PhpStorm) that are able to warn the user about potential issues. In this case, since no return type is documented, we obtain this kind of warning messages:
```
'void' method 'browse' result used less... (Ctrl+F1) 
The value of a void function is most likely used by mistake, because such functions do not have a return value.
```

Would be nice to add these tags :)

Thanks for your work!

**Comment by maxiloc** [comment]
Yes this indeed would be better, feel free to submit a PR
