### ISSUE TITLE
Analytics endpoint missing?

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [algolia/algoliasearch-client-php#339]
Does this client have access to the analytics endpoint?

**Comment by rayrutjes** [comment]
I don't think so, what would you need? I'll try to circle back internally to see if we want to move forward with it.

**Comment by ChrisThompsonTLDR** [comment]
We need access to the analytics data.  I'll just use cURL for now.

**Comment by rayrutjes** [comment]
Sounds like a good alternative for now.
