### ISSUE TITLE
Invalid object attributes: optionalwords

### ISSUE THREAD

**Issue by francorisso** [algolia/algoliasearch-client-php#34]
I'm getting this error when I try to create a request to save an object. I didn't have this error before, it has started around 10 days. Is something I'm doing wrong or is a known bug?
Thanks!

**Comment by Nagriar** [comment]
Hi @francorisso 

Could you paste the content of your request? The "optionalWords" parameter is an index setting, are you sure the error comes from the saveObject? It's maybe triggered by hook of your framework.

**Comment by francorisso** [comment]
Hey, thanks.
The request is this:

{"attributesToIndex":["name"],"attributesForFaceting":["type"],"customRanking":["desc(cnt)"],"minWordSizefor1Typo":3,"minWordSizefor2Typos":7,"optionalwords":"the"}

The saveObject is the one triggering this error.

**Comment by Nagriar** [comment]
Ok the index setting is "optionalWords" :)

**Comment by francorisso** [comment]
Right!!! Sorry and thanks a bunch!!! Closing this one.
