### ISSUE TITLE
Algolia addObject method not working for floats.

### ISSUE THREAD

**Issue by luo-justin** [algolia/algoliasearch-client-php#365]
a simple add object method like this 

   $index->addObject(
              [
                 "avg_rating"=> 1.23456,
                'objectID' => '573'
            ]);

will result in an avg_rating of 0 on my algolia online records. However when i change avg_rating to 1 or 1.0, it is stored as 1. It seems that it cannot store any decimal point numbers. I am using the codeigniter framework. Does anyone else have that issue?

**Comment by julienbourdeau** [comment]
Hi @chunkymankey,

Are you using another package, like a codigniter integration? I assume you are running a very recent version of the client (latest would be the best).

I have tested to be sure and he appear to work. Can you dig a bit deeper and see what is sent to Algolia [here](https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L1239).

**Comment by chunkymankey** [comment]
Hi, 

I echoed out the $body variable that you highlighted, and it outputs the following:

{"params":"query=Subject+Tutoring”}
{"avg_rating":1.2345600000000001017497197608463466167449951171875,"objectID":"573"}
{"avg_rating":1.2345600000000001017497197608463466167449951171875,"objectID":"573"}

This  is using the exact same method in my previous comment. It seems correct.

**Comment by julienbourdeau** [comment]
I don't see how this would be converted to 0, for sure you should see `1.23456` in your dashboard.
About 1.0, it's expected to become 1.
Can you check in your logs (logs tab in your index in Algolia dashboard) what arrived to the API?

**Comment by chunkymankey** [comment]
The response body updates correctly on the logs tab when i add an object:
{
  "avg_rating": 1.2345600000000001017497197608463466167449951171875,
  "objectID": "573"
}
However, the dashboard is still showing a 0. 
This is the JSON answer for object "573" on my dashboard:

{
  "hits": [
    {
      "avg_rating": 0,
      "objectID": "573",
      "_rankingInfo": {
        "nbTypos": 0,
        "firstMatchedWord": 0,
        "proximityDistance": 0,
        "userScore": 0,
        "geoDistance": 0,
        "geoPrecision": 1,
        "nbExactWords": 0,
        "words": 0,
        "filters": 1
      }
    }
  ],
  "nbHits": 1,
  "page": 0,
  "nbPages": 1,
  "hitsPerPage": 10,
  "processingTimeMS": 1,
  "facets": {},
  "exhaustiveFacetsCount": true,
  "exhaustiveNbHits": true,
  "query": "",
  "params": "query=&hitsPerPage=10&page=0&analytics=false&attributesToRetrieve=*&highlightPreTag=%3Cais-highlight-0000000000%3E&highlightPostTag=%3C%2Fais-highlight-0000000000%3E&getRankingInfo=1&facets=%5B%22objectID%22%5D&tagFilters=&facetFilters=%5B%5B%22objectID%3A573%22%5D%5D",
  "index": "Companies",
  "serverUsed": "c5-use-3.algolia.net",
  "parsedQuery": "",
  "timeoutCounts": false,
  "timeoutHits": false
}

**Comment by julienbourdeau** [comment]
Can you try with smaller float? I pretty sure you won't be able to index so many decimals. If it's an average rating, I'd advise to use only one digit after the decimal.

**Comment by chunkymankey** [comment]
I'm not sure why, but when i change it to a smaller float like 1.2, I get the results in my log: 
{
  "avg_rating": 1.1999999999999999555910790149937383830547332763671875,
  "objectID": "573"
}

Why is it not just putting in 1.2? I'm assuming this may be the problem. Is this a php issue?

**Comment by julienbourdeau** [comment]
Yes, it's a PHP issue. Did you hardcode the `1.2` value?

**Comment by chunkymankey** [comment]
I figured out the issue, it is the php version. I am currently using PHP 7.1.8. As soon as I revert to 7.0, the data does not have any precision issues. it sends 1.2 as it should. It seems that php 7.1 has some float precision rounding issues as seen in this thread:
https://stackoverflow.com/questions/42981409/php7-1-json-encode-float-issue 

Basically any json_encode would add a bunch of decimal places to the floating point number. This may be something Algolia wants to look into.

**Comment by julienbourdeau** [comment]
According to [this bug](https://bugs.php.net/bug.php?id=72567), I understand that the issue introduce and was fixed in PHP7.1 but you need to change the default settings of `serialize_precision`.

Usually, we keep our `php.ini` untouch while upgrading. I believe if you switch back to PHP 7.1 and set the `serialize_precision` to `-1`, it should work properly.

<img width="1072" alt="1__tmp__bash_" src="https://user-images.githubusercontent.com/1525636/35267348-42749ada-0026-11e8-9619-94d95c284434.png">

I'll think about the best way to ensure users have the correct settings.

Can be tested and confirmed here: https://3v4l.org/vMP17

**Comment by julienbourdeau** [comment]
For further reference, if anyone is experiencing similar issue. The trick is to **set `serialize_precision` to -1** if you are using PHP 7.1+
