### ISSUE TITLE
Error on the deleteByQuery method when Distinct > 1

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-client-php#37]
In the case the distinct is enabled on an index (with distinct > 1), a call to the method deleteByQuery returns the following error:

```
{
  "message": "invalid distinct value, hitsPerPage * distinct should be <= 1000",
  "status": 400
}
```

We should probably override `distinct=false` at query time when the method performs the search call.

**Comment by Nagriar** [comment]
Already fixed in https://github.com/algolia/algoliasearch-client-php/commit/5327fecaa63091785bfa12dec380b1f35cc59476
