### ISSUE TITLE
filters: filter (X AND Y) OR Z is not allowed, only (X OR Y) AND Z is allowed

### ISSUE THREAD

**Issue by majuansari** [algolia/algoliasearch-client-php#385]
How can I do filtering like following with Algolia ?
`
 'filters' => "((event_type:countries AND countries.id = {$this->city->country_id}) OR (event_type:cities AND countries.id = {$this->city->id}))",
`

Is this possible in Algolia ?

**Comment by julienbourdeau** [comment]
For performance reasons, it isn't possible to have ORs of ANDs. From the documentation:

> For performance reasons, filter expressions are limited to a conjunction (ANDs) of disjunctions (ORs). In other words, you can have ANDs of ORs (e.g. filter1 AND (filter2 OR filter3)), but not ORs of ANDs (e.g. filter1 OR (filter2 AND filter3).

https://www.algolia.com/doc/api-reference/api-parameters/filters/

Usually, the solution is to index the data slightly differently. If you could share some datails about your data, like post a sample records, I'd be happy to help you.

**Comment by TIIUNDER** [comment]
How about providing a solution here

**Comment by julienbourdeau** [comment]
It will depends on what your doing. 
Ideally, you can add more attribute. Instead of storing X in one attribute and Y in another one, you can store the computed value:

```
{
  "category": A, 
  "tag": [B, C],
  "computed": [AB, AC]
} 

This will turn your filter into `AB  OR Z`. 
Please let me know what you think?

**Comment by TIIUNDER** [comment]
Merging the AND-parameters would be possible. But we are using different queries now (which is a good usecase for us). But I will keep that in mind. Thanks!
