### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-php#395]
- Algolia Client Version: 1.25.1
- Language Version: PHP 7.2

### Description
One of the tests failed unexpectedly when I was working on something completely unrelated (#394). Only the PHP 7.2 Travis build failed but I'm not sure it's relevant as the test is probably just flaky.

```
1) AlgoliaSearch\Tests\SearchFacetTest::testSearchForFacetValuesTest
AlgoliaSearch\AlgoliaException: Cannot search in `series` attribute, you need to add `searchable(series)` to attributesForFaceting.
/home/travis/build/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php:1291
/home/travis/build/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php:1105
/home/travis/build/algolia/algoliasearch-client-php/src/AlgoliaSearch/Index.php:752
/home/travis/build/algolia/algoliasearch-client-php/tests/AlgoliaSearch/Tests/SearchFacetTest.php:149
```

### Steps To Reproduce
As it seems to be a flaky test, there's no way to easily reproduce.

**Comment by rayrutjes** [comment]
see #197 
it might be worth asking API team do know more about what those errors could mean.

**Comment by julienbourdeau** [comment]
On the v2 branch the tests are pretty stable, every time they failed was because I broke something 😄 

Although, the test suites is fairly limited, I'll need to implement the common test suite (which shouldn't be flacky).
