### ISSUE TITLE
Partial search in a paragraph

### ISSUE THREAD

**Issue by IAmVinnnn** [algolia/algoliasearch-client-php#398]
I have a paragraph containing a word services, When I am using search method for searching it by passing service it's not return anything but when I am pass exact word services it will return one result. But I want it to return same result for service. 
Is there anything which I can set in the search method?

**Comment by julienbourdeau** [comment]
Hi @IAmVinnnn,

I think the best way would be to use the `ignorePlurals` parameter: https://www.algolia.com/doc/api-reference/api-parameters/

If you only want to do it for `service` and `services`, you can set a [synonyms](https://www.algolia.com/doc/guides/textual-relevance/synonyms/#synonyms-overview).

**Comment by julienbourdeau** [comment]
In this case you will retrieve the entire question attribute. I believe what you're looking for is Highlighting and Snippeting: https://www.algolia.com/doc/guides/searching/highlighting-snippeting/
