### ISSUE TITLE
Simplified search system

### ISSUE THREAD

**Issue by babaorum** [algolia/algoliasearch-client-php#399]
### Description

This is not a feature request.

I started implementing a search system with a Builder, a paginator, etc.
Would you be interested in adding it to the project, if I clean it up a bit and make it valid for PHP 5.3 and above ?

Here is an exemple of how I am using it right now : 
```php
SearchBuilder::new()
    ->in('key1', ['value1', 'value2'])
    ->less('key2', 123)
    ->select(['objectID'])
    ->search()
    ->result()
;
```

**Comment by julienbourdeau** [comment]
Hi @babaorum,

I would really love to see a more expressive way to search but we have a lot to consider when adding this kind of feature.

We maintain clients for many languages (PHP, Java, C#, Go, JavaScript, Ruby, Python, Scala and more) and we'd like to keep them as aligned as possible. There is a few reason for this but the main one is documentation. The whole doc is organized around simple method in both `Client` and `Index` class and it works for all languages: https://www.algolia.com/doc/api-reference/api-methods/search/

I believe that even when we build a v2 of this client, rewriting alomost everything, we'll keep this Client/Index public API. 

We could also add this kind of feature only for one language and without documenting it (or just add mentions in the README but it's really not ideal. Our goal currently is to align all clients as much as possible and make them as easy as possible to maintain.

It would be great if you could publish it as an independant package so people can use your builder. 🚀 

Thanks a lot for your contribution and opening an issue to discuss it before sending the PR.

**Comment by babaorum** [comment]
Ok,
I thought you would prefer to keep your clients aligns.

I will see if I can take some time to create an external package.
If I do it, would you mind doing some review on it ?

If I do it, would you mind doing some review on it ?

Thank you for your quick answer.

**Comment by julienbourdeau** [comment]
Yeah I'll be happy to review it and give you feedback! :)

**Comment by babaorum** [comment]
Je ferme l'issue, plus de questions pour le moment.
