### ISSUE TITLE
What exceptions/error should i catch when using partialUpdateObject() 

### ISSUE THREAD

**Issue by LarsWith** [algolia/algoliasearch-client-php#403]
I am doing a simple update on a row:

```
$index->partialUpdateObject(
        [
          'title' => 'new title',
          'id' => 3,
        ]
      );
```

But if I want to look for exceptions/errors eg

```
try {
$index->partialUpdateObject(
        [
          'title' => 'new title',
          'id' => 3,
        ]
      );
} catch( ..... ) {

}
```

What exception can I check for if it fails?

**Comment by julienbourdeau** [comment]
The package will throw an `AlgoliaSearch\AlgoliaException` if something goes wrong and a `AlgoliaSearch\AlgoliaConnectException` (which extends AlgoliaException) if you cannot connect to our servers.

Is it what you were looking for?

**Comment by LarsWith** [comment]
@julienbourdeau thanks. Yea I guess so, what I want to do is to make sure that I catch any errors during a insert

**Comment by julienbourdeau** [comment]
Yeah that's it 👍
