### ISSUE TITLE
Support user IP and user ID setting

### ISSUE THREAD

**Issue by ivank** [algolia/algoliasearch-client-php#44]
Your api docs state that you have support for IP forwarding and User id tracking - https://www.algolia.com/doc/faq/analytics/will-the-analytics-still-work-if-i-perform-the-search-through-my-backend 
However this sdk does not support it. Do you plan on implementing it? 
I can create a pull request for it if you guys don't have the time.

**Comment by redox** [comment]
Hi @ivank,

yes you're right, that's something we should definitely add and we would be happy to merge your PR :)
