### ISSUE TITLE
algolia Unexpected token 'AND' expected numeric at col 35

### ISSUE THREAD

**Issue by guangzhonghedd01** [algolia/algoliasearch-client-php#442]
Message:algolia Unexpected token 'AND' expected numeric at col 35
Code:400

- Algolia Client Version: 1.25.0
- Language Version: php 7.0
- PHP framework: Laravel 5.5

### Description
Using algolia in Daemons.

**Comment by julienbourdeau** [comment]
Hi,

Could you share the request you're sending to Algolia? If you're using the `where` statement of Laravel Scout, bare in mind [it's very limited](https://laravel.com/docs/5.7/scout#where-clauses) for now, until Nuno releases: https://github.com/algolia/laravel-scout-extended

**Comment by nunomaduro** [comment]
@guangzhonghedd01 Thanks for reporting this issue, I am currently working in [github.com/algolia/scout-extended](https://github.com/algolia/scout-extended). I will keep you posted concerning this issue.
