### ISSUE TITLE
Mock API calls

### ISSUE THREAD

**Issue by bbwebconsult** [algolia/algoliasearch-client-php#48]
There seem to be no way to mock Algolia's API call in the php client. What do you suggest?

**Comment by rayrutjes** [comment]
Hi @bbwebconsult , could you specify your use case?

**Comment by bbwebconsult** [comment]
@rayrutjes We need to test our system that uses Algolia Client without actually calling the service; for functional and unit tests.
Having a way to catch sent requests (to check their content) or fake responses from Algolia (to check that our system handles them correctly) would be very useful in our test suite.

A very good example of this is [Http Guzzle's Mock](http://docs.guzzlephp.org/en/latest/testing.html) utility.

**Comment by rayrutjes** [comment]
@bbwebconsult thank you for this explanation.

For unit testing your system, you will have to test your own classes in isolation and mock your dependencies I guess. You could directly mock Algolia's classes or make another level of abstraction around it.

Regarding integration testing, the purpose being to test the whole system and Algolia's infrastructure being part of it, isn't ok to actually test against the real API? Internally Algolia does a lot of job behind the scene, so faking the results would not reflect the real behaviour of the API. 

To finish you are right about requests inspection, it is actually kind of hard to hook into the transport layer and get info about the raw requests and responses. We definitely have to think about this and we might need to consider Guzzle as an abstraction for the transport in the future.

Feel free to illustrate your needs with some actual testing code of your system, so we can challenge our actual implementation.

**Comment by rayrutjes** [comment]
@bbwebconsult, I hope you found a way to properly test your code! We are closing this issue for now, feel free to open a new one at any time.

**Comment by florentdestremau** [comment]
@rayrutjes I am facing the same problem at the moment, I can't afford to hit the production in all of my tests, let alone fixtures...I would like to

- disable the doctrine subscriber in test env only
- return a predefined array as hits from a search

I am trying to get this done, will keep posted. One thing that would help this would be to use an interface instead of a service call so that we could override the service with dummy requests that don't use api calls.

**Comment by bboure** [comment]
@florentdestremau Are you using Codeception ?
To solve this issue I used [Stub](http://codeception.com/docs/reference/Stub) from codeception

````php
$client = Stub::construct(
                '\AlgoliaSearch\Client',
                ['fakeApplicationID', 'fakeApiKey'],
                [
                    'doRequest' => function () {
                        // return here the expected hit.
                        return [];
                    }
                ]
            );
````
