### ISSUE TITLE
Clear Cache Possible ?

### ISSUE THREAD

**Issue by fvoverscan** [algolia/algoliasearch-client-php#492]
Hi,
is it possible to clear the cache ?

Thanks

**Comment by nunomaduro** [comment]
Hi @fvoverscan,

Yes it's possible to clear the cache. In order to give you the best solution, can you first detail your problem?

**Comment by fvoverscan** [comment]
Hi,

When i search in my index, it's seems that i get an old version of my items because not all of them are updated. For exemple, i have updated pictures of some items and when i search in the index, some are ok but other not.

I'm thinking to clear the cache.

Could you tell me how to do it ?

Thanks

**Comment by nunomaduro** [comment]
@fvoverscan Thanks for the quick reply. There is **no cache** in the search. Probably there is some problem in your implementation. Let's figure it out together. Some questions:

Are you using some framework integration or you are using this API Client directly?

When you update pictures, they get all updated? You can know that using the [Algolia Dashboard](https://www.algolia.com/dashboard).

**Comment by fvoverscan** [comment]
Hi @nunomaduro,
The bug has been identified on the framework i use and they will resolve it.
Thanks for your reply.
