### ISSUE TITLE
Call to protected method SearchIndex::addObjects in the docs

### ISSUE THREAD

**Issue by OptimusCrime** [algolia/algoliasearch-client-php#508]
- Algolia Client Version: dev-latest
- Language Version: Irrelevant

README.md and the official docs makes use of `SearchIndex::addObjects`, however, this method was changed to protected in 5c94958b1ee04eb3eb804c9c5412f86fc3172e46, and the correct method should be `SearchIndex::saveObjects` (as far as I can tell).

**Comment by nunomaduro** [comment]
Thanks for reporting this issue! Nice feedback, going to address this with our docs team. 👍

**Comment by OptimusCrime** [comment]
It is wrong in the readme in this repo as well.

**Comment by nunomaduro** [comment]
@OptimusCrime Yes. It will be updated soon as the doc get updated.
