### ISSUE TITLE
browseObjects() Iterator keys not being set properly

### ISSUE THREAD

**Issue by bgurney** [algolia/algoliasearch-client-php#514]
- Algolia Client Version: 2.2.0
- Language Version: PHP 7.1

### Description
When using the `Algolia\AlgoliaSearch\SearchIndex@browseObjects` method, the Iterator that is returned doesn't increment the keys properly. I think you need to call `$this->key++` at the top of `Algolia\AlgoliaSearch\Iterators\AbstractAlgoliaIterator@next`

### Steps To Reproduce
Try to use `iterator_to_array()` on the Iterator that is returned. I know you can get round this by passing a second `false` parameter to the method, but it feels like an oversight since you've got a `$this->key` property on your Iterator.

**Comment by julienbourdeau** [comment]
Hi @bgurney,
Thank you this is definitely a bug, I totally forgot the increment the key 😱 Let me open a PR and add a test 👌

**Comment by sleicester** [comment]
Awesome @julienbourdeau, I was going to whip a PR for this but you were too quick. I like in the test the assertions against each key, very precise and tidy.
