### ISSUE TITLE
Missing Code Quality tools

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#519]
This issue was created to be a `good first issue`. The **Goal** is to study the inclusion of some `require-dev` dependencies to analyse and detect issues in source for us.

Some proposals:

- phpstan
- phploc
- phpmd

After discussion, we may want you to perform a pull request that includes the tool in the project. You may also have to update the `travis.yml`.

**Comment by TomKlotzPro** [comment]
I'm taking this issue.

**Comment by TomKlotzPro** [comment]
@nunomaduro can we close this issue ?

**Comment by nunomaduro** [comment]
@TomKlotzPro Not yet. There still some to add 👍

**Comment by damcou** [comment]
Added on the last version of the client
