### ISSUE TITLE
Test client in high load scenarios benchmark tools

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#522]
### Description

This issue should address testing our API Client in `high load scenarios` using benchmark tools.

**Goal**: Make sure that the code/algorithm is as efficient as possible concerning time, CPU usage, etc. If something should be improved, perform a Pull Request.

Take in mind, that currently,  we have the `guzzle` and the `traditional` requester. So both scenarios must be tested.

**Comment by kiler129** [comment]
I can recommend blackfire - with 1.x there are many points where improvements can be made. We're just starting to use search on the backend (and indexing wasn't critical to profile) and we see places which are significantly contributing to the hotpath.

**Comment by nunomaduro** [comment]
## Environment
- MacBook Pro (15-inch, 2018)
- 2,6 GHz Intel Core i7
- 16 GB 2400 MHz DDR4
- Network Wifi at Algolia’s Paris office/My home

## The benchmarks
We have benchmarked three versions of our php client:

- 1.28.0
- 2.2.3
- 2.2.3 with Guzzle 

For the test, we have used a PHP script that fires 3 processes, one per client type, in parallel. For each process, the script will run 30000 iterations of “multipleQueries” method using the endpoint “/1/indexes/{client-type}/queries”) with the following payload:

```
{"requests": [{"indexName": "bench-{client-type}", "query": ""}]}
```

This document describes the raw results together with environment and some details on the tests themselves.

## Comparison PHP v1 ⇔ PHP v2

Sharing the same client instance:  Revision 1 - From Paris Office.

Client | Mean | Per90 | Per95 | Per99
-- | -- | -- | -- | --
1.28 | 19ms | 23ms | 26ms | 45ms
2.23 | 19ms | 23ms | 26ms | 45ms
2.23 Guzzle | 18ms | 20ms | 23ms | 56ms

Sharing the same client instance:  Revision 2  - From my home.

Client | Mean | Per90 | Per95 | Per99
-- | -- | -- | -- | --
1.28 | 16ms | 18ms | 21ms | 32ms
2.23 | 16ms | 18ms | 22ms | 32ms
2.23 Guzzle | 14ms | 16ms | 18ms | 27ms

Sharing the same client instance:  Revision 3  - From my home.

Client | Mean | Per90 | Per95 | Per99
-- | -- | -- | -- | --
1.28 | 15ms | 16ms | 18ms | 25ms
2.23 | 15ms | 17ms | 18ms | 25ms
2.23 Guzzle | 13ms | 15ms | 17ms | 25ms

Creating a new $client instance per iteration: Revision 1.

Client | Mean | Per90 | Per95 | Per99
-- | -- | -- | -- | --
1.28 | 87ms | 106ms | 111ms | 128ms
2.23 | 32ms | 22ms | 19ms | 16ms
2.23 Guzzle | 26ms | 17ms | 15ms | 13ms

Creating a new $client instance per iteration: Revision 2.

Client | Mean | Per90 | Per95 | Per99
-- | -- | -- | -- | --
1.28 | 88ms | 106ms | 110ms | 124ms
2.23 | 14ms | 16ms | 17ms | 26ms
2.23 Guzzle | 13ms | 14ms | 15ms | 21ms

Conclusions: The PHP Client v2 **noticeably** faster than v1.
