### ISSUE TITLE
Symfony HttpClient adapter

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-client-php#525]
Symfony release its new HttpClient: https://github.com/symfony/http-client/

I'm wondering if it would make sense to have an adapter for it, next to the PHP5.3 and guzzle ones.

As far as I understood, it's not PSR compliant so it might require a bit more work, to convert [requests and responses](https://github.com/algolia/algoliasearch-client-php/tree/master/src/Http).

The main reason I see to add it, is *if* it brings value to our [SearchBundle](htts://github.com/algolia/search-bundle).

**Comment by kiler129** [comment]
It's fast. Blazing fast. The current Guzzle implementation is not bad and I think we should wait instead on jumping on the hype right now ;)

**Comment by kiler129** [comment]
Who am I lying to.... of course as a developer I will like to test how does it work with newest toy 👍 

Check the PR guys: 
https://github.com/algolia/algoliasearch-client-php/pull/526 - it was actually very easy to implement and passes the whole test suite.

**Comment by nunomaduro** [comment]
This was a good discussion team, but after some thoguths on this there is no plans of adding this to this low level client at the moment.

Maybe later we could consider having this on the `search_bunddle`. Thanks for the discussion tho.
