### ISSUE TITLE
Implement settings tests of CTS

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#527]
We would like to implement a `settings test` as described bellow. 

It's up to the developer the place where the test should be. Keep in mind that you may have to remove some tests that already exist.

#### Test description

* Instantiate the client and index `settings` and keep the generated index name (which will be used as a prefix of the replica indices)
* Add one record to create the index with **saveObject**
* Set the settings with the following parameters with **setSettings** and collect the taskID

| Setting                             | Value                                                                                                                       |
| ----------------------------------- | --------------------------------------------------------------------------------------------------------------------------- |
| `searchableAttributes`              | `[ "attribute1", "attribute2", "attribute3", "ordered(attribute4)", "unordered(attribute5)" ]`                              |
| `attributesForFaceting`             | `[ "attribute1", "filterOnly(attribute2)", "searchable(attribute3)" ]`                                                      |
| `unretrievableAttributes`           | `[ "attribute1", "attribute2" ]`                                                                                            |
| `attributesToRetrieve`              | `[ "attribute3", "attribute4" ]`                                                                                            |
| `ranking`                           | `[ "asc(attribute1)", "desc(attribute2)", "attribute", "custom", "exact", "filters", "geo", "proximity", "typo", "words" ]` |
| `customRanking`                     | `[ "asc(attribute1)", "desc(attribute1)" ]`                                                                                 |
| `replicas`                          | `[ indexname + "_replica1", indexname + "_replica2" ]`                                                                      |
| `maxValuesPerFacet`                 | `100`                                                                                                                       |
| `sortFacetValuesBy`                 | `"count"`                                                                                                                   |
| `attributesToHighlight`             | `[ "attribute1", "attribute2" ]`                                                                                            |
| `attributesToSnippet`               | `[ "attribute1:10", "attribute2:8" ]`                                                                                       |
| `highlightPreTag`                   | ``"<strong>"``                                                                                                              |
| `highlightPostTag`                  | ``"</strong>"``                                                                                                             |
| `snippetEllipsisText`               | ``" and so on."``                                                                                                           |
| `restrictHighlightAndSnippetArrays` | `true`                                                                                                                      |
| `hitsPerPage`                       | `42`                                                                                                                        |
| `paginationLimitedTo`               | `43`                                                                                                                        |
| `minWordSizefor1Typo`               | `2`                                                                                                                         |
| `minWordSizefor2Typos`              | `6`                                                                                                                         |
| `typoTolerance`                     | `false`                                                                                                                     |
| `allowTyposOnNumericTokens`         | `false`                                                                                                                     |
| `ignorePlurals`                     | `true`                                                                                                                      |
| `disableTypoToleranceOnAttributes`  | `[ "attribute1", "attribute2" ]`                                                                                            |
| `disableTypoToleranceOnWords`       | `[ "word1", "word2" ]`                                                                                                      |
| `separatorsToIndex`                 | `"()[]"`                                                                                                                    |
| `queryType`                         | `"prefixNone"`                                                                                                              |
| `removeWordsIfNoResults`            | `"allOptional"`                                                                                                             |
| `advancedSyntax`                    | `true`                                                                                                                      |
| `optionalWords`                     | `[ "word1", "word2" ]`                                                                                                      |
| `removeStopWords`                   | `true`                                                                                                                      |
| `disablePrefixOnAttributes`         | `[ "attribute1", "attribute2" ]`                                                                                            |
| `disableExactOnAttributes`          | `[ "attribute1", "attribute2" ]`                                                                                            |
| `exactOnSingleWordQuery`            | `"word"`                                                                                                                    |
| `enableRules`                       | `false`                                                                                                                     |
| `numericAttributesForFiltering`     | `[ "attribute1", "attribute2" ]`                                                                                            |
| `allowCompressionOfIntegerArray`    | `true`                                                                                                                      |
| `attributeForDistinct`              | `"attribute1"`                                                                                                              |
| `distinct`                          | `2`                                                                                                                         |
| `replaceSynonymsInHighlight`        | `false`                                                                                                                     |
| `minProximity`                      | `7`                                                                                                                         |
| `responseFields`                    | `[ "hits", "hitsPerPage" ]`                                                                                                 |
| `maxFacetHits`                      | `100`                                                                                                                       |
| `camelCaseAttributes`               | `[ "attribute1", "attribute2" ]`                                                                                            |
| `decompoundedAttributes`            | `{ "de": ["attribute1", "attribute2"], "fi": ["attribute3"] }`                                                              |
| `keepDiacriticsOnCharacters`        | `"øé"`                                                                                                                      |

* Wait for the collected tasks to terminate with **waitTask**
* Get the settings with **getSettings** and check that they correspond to the ones that were inserted
* Set the settings with the following parameters with **setSettings** and collect the taskID

| Setting           | Value          |
| ----------------- | -------------- |
| `typoTolerance`   | `"min"`        |
| `ignorePlurals`   | `["en", "fr"]` |
| `removeStopWords` | `["en", "fr"]` |
| `distinct`        | `true`         |

* Wait for the collected tasks to terminate with **waitTask**
* Get the settings with **getSettings** and check that they correspond to the ones that were inserted and overridden

**Comment by TomKlotzPro** [comment]
I'm going to take this issue, pull request is coming next days.

**Comment by nunomaduro** [comment]
This issue has been fixed.
