### ISSUE TITLE
Guzzle 5 automatically wired but it's not supported

### ISSUE THREAD

**Issue by DelecroixQuentin** [algolia/algoliasearch-client-php#537]
- Algolia Client Version: 2.2.3
- PHP Version: 7.2

### Description
I am using algoliaserach-client-php with Prestashop, which includes Guzzle 5. The Algolia client finds and tries to use Guzzle, but it is integrated for Guzzle 6 ...

Except edit the Algolia client, is there a solution to choose the HTTP client to use rather than checking if Guzzle is installed (since the configuration maybe?)?

**Comment by nunomaduro** [comment]
Hi @DelecroixQuentin,

That's a bug IMO. Here is the temporary workaround:

```php
$httpClient = new \Algolia\AlgoliaSearch\Http\Php53HttpClient();

\Algolia\AlgoliaSearch\Algolia::setHttpClient($httpClient);

$client = \Algolia\AlgoliaSearch\SearchClient::create('foo', 'bar');
```

**Comment by DelecroixQuentin** [comment]
Hi @nunomaduro,

That works fine with your temporary workaround.
Thanks!

**Comment by julienbourdeau** [comment]
Indeed we should probably check the guzzle version instead of checking for class_exists! 👍

**Comment by TomKlotzPro** [comment]
I'm on it.
