### ISSUE TITLE
[2.0] Add `count` method to ObjectIterator

### ISSUE THREAD

**Issue by borealsmith** [algolia/algoliasearch-client-php#538]
Hi 

I would like to submit a PR to add a public method to the ObjectIterator which enables getting the number of the records in the index available in the api response when the broweObjects method is called. something along these lines

`public function getNbHits()
    {
        return isset($this->response['nbHits']) ? $this->response['nbHits'] : null;
    }`

Would that be acceptable ?

Thank you.

**Comment by nunomaduro** [comment]
@borealsmith Thanks for this proposal.

Could you tell me the use case of this?

**Comment by borealsmith** [comment]
@nunomaduro Thank you. Actually I would like to use it for the scout-extemnded reimport command. the only way I can do it right now is to iterate through the collection and count the number of objecs. Bu I noticed that the information is already available in the api response.

**Comment by nunomaduro** [comment]
@borealsmith Probably better implement a count method on the SearchIndex object.

```php
    /**
     * Count the number of objects in the index.
     *
     * @return int
     */
    public function countObjects()
    {
        return (int) $this->search('')['nbHits'];
    }
```

**Comment by borealsmith** [comment]
@nunomaduro that is the thing I was initially looking for. My understanding of the api is that search method with and empty string query will return no records vs brows method which will return the entire set of records. Therefore i suggested a count method on the ObjectIterator.  I also tested both methods on one of my indexes and the tests confirm my understanding

**Comment by borealsmith** [comment]
$index->search('')
`array:9 [
  "hits" => []
  "page" => 0
  "nbHits" => 0
  "nbPages" => 0
  "hitsPerPage" => 20
  "exhaustiveNbHits" => true
  "processingTimeMS" => 1
  "query" => ""
  "params" => ""
]
vs

$temporaryIndex->browseObjects(['query' => '']);`
...
"nbHits" => 4
    "page" => 0
    "nbPages" => 1
    "hitsPerPage" => 1000
    "processingTimeMS" => 1
    "query" => ""
    "params" => "hitsPerPage=1000"
  ]
`

`

**Comment by borealsmith** [comment]
Well  the doc for the search method also says:

The search query only allows for the retrieval of up to 1000 hits. If you need to retrieve more than 1000 hits (e.g. for SEO), you can either leverage the Browse index method or increase the paginationLimitedTo parameter.

And

An empty query can be used to fetch all records. (Q1 i.e up to 1000 ? Q2 why I dont get any results when I search in my index with and empty quuery? )

**Comment by nunomaduro** [comment]
If you do a empty search, the result `nbHits` will contain the count of all index.

**Comment by borealsmith** [comment]
well, not in the example I pasted above ie empty search nbHits => 0 vs empty browse objects nbHits => 4 over the very same index.

**Comment by nunomaduro** [comment]
@borealsmith We are working internally at Algolia in a package that will provide this feature. So, at the moment: no plans on having this in this client.

**Comment by borealsmith** [comment]
@nunomaduro Thanks for letting me know. No pb.

**Comment by nunomaduro** [comment]
@borealsmith And thanks for the proposal buddy! 👍
