### ISSUE TITLE
Missing exceptions documentation on the upgrade-guide

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#542]
Just saw that in the upgrade guide there is no reference to the change of the namespace on exceptions in the major version v2.

Normally, we should something like this: https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/python/?language=python#exceptions

**Comment by TomKlotzPro** [comment]
i'm on it.

**Comment by TomKlotzPro** [comment]
The documentation was merged. We can close it @nunomaduro
