### ISSUE TITLE
Breaking change in 2.2.5

### ISSUE THREAD

**Issue by WhiteWolf99** [algolia/algoliasearch-client-php#547]
- Algolia Client Version: 2.2.5
- Language Version: php 5.5.9

### Description
Patch release 2.2.5 results in syntax error on older PHP version. Patch releases should not include breaking changes.
` if (class_exists('\GuzzleHttp\Client') && 6 === (int) \GuzzleHttp\Client::VERSION[0]) `

Here `VERSION[0]` syntax will result in syntax error in PHP 5.5.9

**Comment by nunomaduro** [comment]
Can you re-test it @WhiteWolf99 ?
