### ISSUE TITLE
Disjunctive facets

### ISSUE THREAD

**Issue by olup** [algolia/algoliasearch-client-php#556]
Hey !

Thanks for the great implementation.

My company is trying to use the php client in order to get facets count with `disjunctive_facets`. And on top of that we need to filter by facets and by regular filters.

Is there a reason why v1.x does not allow to add `$disjunctive_facets` in cunjunction with some regular filters ?

Is `$disjunctive_facets` available in v2 ? I don't see anything about it in the codebase, other than it's coming soon.

Cheers !

**Comment by TomKlotzPro** [comment]
Hello @olup, 

Thanks for reporting this issue. 

>`Is there a reason why v1.x does not allow to add $disjunctive_facets in cunjunction with some regular filters ?` 

We're are currently investigating this question. We will answer as soon as possible. 

>`Is $disjunctive_facets available in v2 ?

At the moment no. But, we are currently considering to implement this method for the version 2. We will come back to this issue once we have an exact date.

Don't hesitate to reach us if you have any further questions.

**Comment by olup** [comment]
Ok thanks. Anyway, we are ending up implementing it ourselves from the v2
client. Maybe a pr in the future ?
Cheers.

**Comment by TomKlotzPro** [comment]
Hello @olup, we decide it was important to implement it for the v2, a pull request will be opened in the future. 
If in any case, you need to implement it for v2 `PHP-Client`, here is a [gist].(https://gist.github.com/maxiloc/7f904f33fbc60913b3531c9122472abf)
Cheers,

**Comment by olup** [comment]
Cheers ! We ended up implementing it ourselves too.

**Comment by chloelbn** [comment]
I'm closing this issue as a solution has been provided
