### ISSUE TITLE
GZIP on POST/PUT requests

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-php#563]
https://github.com/algolia/algoliasearch-client-specs-internal/issues/30

**Comment by TomKlotzPro** [comment]
cc @aseure [561](https://github.com/algolia/algoliasearch-client-php/issues/561)

**Comment by chloelbn** [comment]
Duplicate of https://github.com/algolia/algoliasearch-client-php/issues/561, I'm closing this issue
