### ISSUE TITLE
Linter do not sort imports alphabetically

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#566]
**Issue**: When running `./vendor/bin/php-cs-fixer fix`, the linter do not sort imports alphabetically.

**Goal**: Update `.php-cs.dist` to make sure it sort imports alphabetically, using ascending order.

**Comment by TomKlotzPro** [comment]
hello @nunomaduro, why we don't add this annotation to our .php-cs.dist `@PhpCsFixer`.
Few concern about adding this, this rule `'php_unit_test_class_requires_covers' ` will generate by default this annotation `@coversNothing` in php-unit-test doc, we should turn it to false.

**Comment by chloelbn** [comment]
Closing this issue as it will be handled in the Quality tools PR https://github.com/algolia/algoliasearch-client-php/pull/560
