### ISSUE TITLE
Retryable connection timeouts should retry in the same host with bigger timeouts

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#575]
Looking at the retry specs, we see that:
```
When retrying, use the next host in your array.
When retrying because of a timeout, raise the timeouts like this:
number_of_tries * base_timeout
Example: Search (5s timeout) → Search timeout → Search (10s timeout) → Repeat.
```

At the moment, on the PHP API Client connection timeouts exceptions are retrying in a different host.

**Goal**: 

1. Isolate connection timeouts exceptions and retry in the same host
2. Multiple timeouts by the number of tries
3. Add a tests on it

Implementation on C#: https://github.com/algolia/algoliasearch-client-csharp/blob/42ab1842f859df87482602b12d5cb714bfa8ec71/src/Algolia.Search/Transport/HttpTransport.cs#L118

**Comment by chloelbn** [comment]
I've made some investigation but my understanding is that you keep on looping on hosts when you get a retriable error, but you raise the timeout for the next time. Maybe I'm confused by the implementation on the PHP client though, I'd like your input on this @aseure @Ant-hem if you don't mind

**Comment by damcou** [comment]
Will reopen it if needed
