### ISSUE TITLE
feat: add contextual rules

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#578]
**TL;DR**: The `condition` field on rules is now optional.

Actions required:

- Update the `cts` with the information on : [#71](https://github.com/algolia/algoliasearch-client-specs-internal/pull/71/files)
- On strongly typed clients, update types in query rules, as the `condition` field in rules is now **optional**

- [Python test suite update](https://github.com/algolia/algoliasearch-client-python/pull/450/files)

**Comment by chloelbn** [comment]
OK for PHP
