### ISSUE TITLE
docs: wrong snippet on default headers

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#585]
On the website the following highlighted snippet is incorrect.  Let's make sure we address this. 
 
<img width="701" alt="Screen_Shot_2019-09-10_at_1 27 12_PM" src="https://user-images.githubusercontent.com/5457236/64648737-72fa8a80-d413-11e9-8b4a-d95afac0d156.png">

**Comment by chloelbn** [comment]
adressed in https://github.com/algolia/doc/pull/5045

**Comment by damcou** [comment]
Solved
