### ISSUE TITLE
[IMPORTANT] Remove latest 1.7.1.1 release

### ISSUE THREAD

**Issue by vinkla** [algolia/algoliasearch-client-php#60]
The minor fixes release `1.7.1.1` should be deleted and retagged as `1.7.2`.

Also the `1.7.1` release introduced new features and should've been tagged as `1.8.0`. We shouldn't change this release since it is already tagged but we need to think of this in the future before tagging new versions of the package.

`1.3.2` = `MAJOR.MINOR.PATCH` http://semver.org/

Ping @maxiloc @redox

**Comment by vinkla** [comment]
Ping @maxiloc @redox

**Comment by vinkla** [comment]
Also, it seems version `1.6.3` was released after `1.7.0`?

<img width="523" alt="qjrwgl6y3m0snzz_c4-bcxkc59ieokzsv6np_t24pyjdpwdqbcurhfeldqf0nnn6ydzx8zvfrovxuf9nxlncrn0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85" src="https://cloud.githubusercontent.com/assets/499192/13290467/fb1af9ce-db13-11e5-81a3-33cbb68c8616.png">

**Comment by maxiloc** [comment]
Indeed we did some bad thing with versioning, we'll improve that in the future.
We'll republish a new version 1.8.0 version

**Comment by vinkla** [comment]
Oka, good. Don't forget to delete version 1.7.1.1!
