### ISSUE TITLE
saveObject() - IDN conversion failed

### ISSUE THREAD

**Issue by nserbass** [algolia/algoliasearch-client-php#603]
- Algolia Client Version: 4.0.0
- Language Version: PHP

### Description
When I try to save an object, I receive the following error:
```
In Client.php line 241:
                       
  IDN conversion failed 
```
I've been debugging my code and I've seen that the error is throwned by the guzzle client.

My code:
```php
final class AlgoliaClient
{
    private $client;

    public function __construct()
    {
        $this->client = SearchClient::create(
            getenv('ALGOLIA_APP_ID'),
            getenv('ALGOLIA_API_KEY')
        );
    }

    public function index(string $indexName)
    {
        return $this->client->initIndex($indexName);
    }
}
```

```php
$client = new AlgoliaClient()
$index = $client->index(self::SEARCH_INDEX);
$index->saveObject($item->toSearchArray())->wait();
``` 
``` php
public function toSearchArray(): array
 {
        return [
            'objectID'  => $this->id->value(),
            'title'         => $this->slug->value(),
            'slug'        => $this->releaseYear
        ];
}
```

**Comment by chloelbn** [comment]
Hello @nserbass, thank you for your feedback. Unfortunately I can't seem to reproduce the issue, does your index name contains special characters?

**Comment by nserbass** [comment]
Hi @chloelbn thak you for your answer. No, my index name is `media`. Is there any restriction for object values? for instance, my objectID is an UUID string.

**Comment by nserbass** [comment]
Hi @chloelbn, I've found out what was going on. The `getenv()` wasn't working properly so I've changed by native php function `$_ENV` and it's working right now!
