### ISSUE TITLE
Query rule : promoted hits with position 

### ISSUE THREAD

**Issue by TomKlotzPro** [algolia/algoliasearch-client-php#613]
### Description
After testing this [snippet](https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/promote-hits/#api-1) for the maximum value of position on the php playground. I retrieve this specific error : 

```
Expecting an array (in `[0].consequence.promote`) (near 1:113)  
```
or 
```
Invalid `objectID`: bad format (expecting `[A-Za-z0-9_-]+`) (in `[0].objectID`) (near 1:32) 
```
### Steps To Reproduce

Use the playground https://github.com/algolia/api-clients-playground/tree/master/php

And try to run this snippet : 
https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/promote-hits/#api-1

It works perfectly with the Go Client.

**Comment by DevinCodes** [comment]
Found the issue: it needs to be an array of arrays. Updating the snippet 👍

**Comment by DevinCodes** [comment]
Since it's an issue with the snippet in the Algolia docs, and not the client, I'm closing this issue.
