### ISSUE TITLE
Ensure correct serialization of searchSynonyms' type query parameter

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-php#617]
When performing a `index.searchSynonyms()` call, a [`type` query
parameter](https://www.algolia.com/doc/rest-api/search/#method-param-type) can
be passed to restrict the type(s) of synonyms one wants to search for.

@maxiloc reported us that the Java implementation is accepting an array of
strings for this parameter. However, the engine only accepts a comma-separated
string for this. We then need to double check the implementation of the
serialization of this parameter and provide a fix if needed.

**Comment by chloelbn** [comment]
`type` is treated as a regular `requestOptions` parameter so no need to fix anything here
