### ISSUE TITLE
Missing support for Guzzle 7

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-php#619]
Soon, Guzzle 7 will be out, and we need to add support to it: https://packagist.org/packages/guzzlehttp/guzzle

**Comment by ostrolucky** [comment]
https://github.com/algolia/algoliasearch-client-php/pull/621#issuecomment-634058068 mentions current adapter works with guzzle 7. Shall this issue be closed then?

**Comment by chloelbn** [comment]
no because there are some breaking changes in version 7 used outside of the adapter that need to be addressed
