### ISSUE TITLE
Expose rule.consequence.promote.objectIDs string array

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-php#623]
On top of the existing `objectID` (singular) string field, a new `objectIDs`
(plural) string array field is now be exposed in the `rule.consequence.promote`
Rule object representation. This lets the user easily promote a full group of
objects without letting some priority conflicts to shift some objects at the end
of the promoted object list.

**Comment by nunomaduro** [comment]
This is a non-typed API Client. Therefore, nothing to perform here.
