### ISSUE TITLE
Object forbidden at this position

### ISSUE THREAD

**Issue by joshuabaker** [algolia/algoliasearch-client-php#624]
We’re getting a bad request exception coming back from the API when including a `params` object in the query.

**Error**

```
Object forbidden at this position near line:1 column:56
```

**Code**

What our code looks like:

```php
$client = SearchClient::create($appId, $key);

$response = $client->multipleQueries([
	[
	    'indexName' => 'anyIndex',
	    'params' => [
	        'tagFilters' => ''
	    ],
	],
]);
```

**Request**

The request body (and the point that the exception references):

```json
{"requests":[{"indexName":"dev_opportunities","params":{"tagFilters":""}}]}
                                                       ↑
```

- If we remove the `params` object the request is successful
- According to the [docs](https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/#method-param-query-object) `params` is valid
- The `params` is also present in the JavaScript client request that we’re trying to proxy (for security reasons)

---

- Algolia Client Version: 2.6.1
- Language Version: PHP

**Comment by joshuabaker** [comment]
Looking at the same method in the JavaScript client I can see that the `params` must be encoded as a query string, which [isn’t what’s documented](https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/#method-param-query-object).

Ideally, the PHP client should handle this like the JavaScript client does in order to have API parity.

#### Interim Fix

```php
$requests = array_map(static function ($request) {
    if (isset($request['params'])) {
        $request['params'] = http_build_query($request['params']);
    }

    return $request;
}, $requests);
```

**Comment by chloelbn** [comment]
Hi @joshuabaker, and thanks a lot for bringing this issue to our attention! If you want to, feel free to submit a PR to fix this problem. Otherwise, we'll handle it as soon as possible.
Have a good day!
