### ISSUE TITLE
[Testing] Tests fails for PRs due to missing applicationId env variable.

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-client-php#63]
I have some work in progress over here: #62 
The problem is that travis does not seem to be aware of any applicationId, and I suppose the apiKey is not injected either.

Locally everything works fine, is there a trick here to tell travis about my custom appId and apiKey so my tests turn to green?

**Comment by rayrutjes** [comment]
@maxiloc have you changed something recently? Seems to work now?

**Comment by maxiloc** [comment]
No not me :smile:

**Comment by rayrutjes** [comment]
Ok, maybe is it linked to the fact that I now have access to Travis, so this issue is still valid for external contributors I suppose.

**Comment by JanPetr** [comment]
Yes, it's definitely because you joined Algolia. Secret enviroment variables are not injected when you create a PR from a fork. From [Travis docs](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables): `Encrypted variables are not added to untrusted builds such as pull requests coming from another repository.`

It would be huge security leak. Probably there is nothing we can do if you don't want to disclose your private Algolia credentials. And nobody wants that ;)

**Comment by rayrutjes** [comment]
Related to https://github.com/travis-ci/travis-ci/issues/1946
There seems to be no solution for now...

**Comment by redox** [comment]
I more and more think we should just inline a test appid/apikey in plain text in our travis.yml files targeting a test cluster (+ eventually remove the underlying data every day - just in case someone start using it) -> but it's really confusing to have all tests failing while submitting a PR.

@asurak What do you think?

**Comment by asurak** [comment]
Like adding the admin API key in plaintext?

**Comment by redox** [comment]
> Like adding the admin API key in plaintext?

Yes. The credentials in clear text in the `travis.yml` or in the code, targeting a test cluster.

**Comment by asurak** [comment]
Then I'm against this ;)

**Comment by redox** [comment]
> Then I'm against this ;)

Do you think about something else in order to make sure our tests run on PRs (mocking is not an option).

**Comment by asurak** [comment]
Unfortunately not. The reasons why Travis does not expose the secrets to PRs are valid.

**Comment by redox** [comment]
> The reasons why Travis does not expose the secrets to PRs are valid.

I know :) Just thinking about the best developer experience here.

**Comment by asurak** [comment]
Can we make the tests fail gracefully?

**Comment by vvo** [comment]
You can have a search only set of tests for external PRS. full tests when merged into develop so you check everything.

**Comment by JanPetr** [comment]
> You can have a search only set of tests for external PRS. full tests when merged into develop so you check everything.

But we would have nothing to search for as we are not able to push any data to index without admin API key

**Comment by rayrutjes** [comment]
The search isn't even tested at this point though.

**Comment by rayrutjes** [comment]
Let's close this one because there is no way to safely resolve it.
