### ISSUE TITLE
getApiKey($optional_index) for local-key support

### ISSUE THREAD

**Issue by drzraf** [algolia/algoliasearch-client-php#630]
- Algolia Client Version: 1.23.0
- Language Version: PHP 7

### Description
I found that contrary to other keys, **local-**keys can't reach `algolia.net/1/keys/%key%` (403)
Still, they can reach `algolia.net/1/indexes/%index%/keys/%key%` but no such method exist neither in v1 nor, AFAICT, in v2.

It would be useful if this method could be provided so that local-keys can be used too.

### Steps To Reproduce
- Setup a **local** key
- Call `getApiKey` / `getUserKeyACL`

**Actual**: failed (403) `"Invalid Application-ID or API key"`
**Expected**: Something like `getApiKey($key, $index)` would succeed

**Comment by julienbourdeau** [comment]
local keys are softly-deprecated, I'd recommend not using them. We remove this feature in v2. You can still call the endpoint manually but we'd rather not add a dedicated method.
