### ISSUE TITLE
Implement retry until success for restore_api_key() call in CTS test

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-php#634]
Because of the way Algolia is designed, performing a `restoreApiKey` may not
succeed because the previous `deleteApiKey` takes some time to get propagated
to all Algolia servers, giving us the following response: `[404] Key already
exists`.

To prevent that, we need to change the `testApiKeys` CTS test, if implemented,
to retry even on `[404] Key already exists` response.

**Comment by chloelbn** [comment]
Closing as PHP client doesn't implement CTS
