### ISSUE TITLE
Propagation of exceptions in ApiWrapper

### ISSUE THREAD

**Issue by DelecroixQuentin** [algolia/algoliasearch-client-php#638]
Hello,

I wanted to implement a function that checks the validity of the credentials provided by a user.
Here is my function to do this:
```php
public function checkCredentials()
{
    try {
        $this->client->listIndices();
    } catch (UnreachableException $e) {
        throw new PrestaShopException($e->getMessage());
    }
    return true;
}
``` 
The problem is that in `ApiWrapper.php`, the `read`, `write` and `send` methods do not propagate exceptions that the `request` method raises. Therefore, we ("PHP client API" user) cannot handle exceptions.

Stack Trace:
```
Algolia\AlgoliaSearch\Exceptions\UnreachableException:
Impossible to connect, please check your Algolia Application Id.

  at modules/rocketalgolia/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:187
  at Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->request('GET', '/1/indexes/', object(RequestOptions), array('-dsn.algolia.net', '-2.algolianet.com', '-1.algolianet.com', '-3.algolianet.com'), 5)
     (modules/rocketalgolia/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:78)
  at Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->read('GET', '/1/indexes/', object(RequestOptions))
     (modules/rocketalgolia/vendor/algolia/algoliasearch-client-php/src/SearchClient.php:200)
  at Algolia\AlgoliaSearch\SearchClient->listIndices()
     (modules/rocketalgolia/src/Algolia/Algolia.php:69)
```

wdyt about propagate exceptions raise in `request` method ?

**Comment by DelecroixQuentin** [comment]
Hi,
Ping @chloelbn @e1himself

**Comment by e1himself** [comment]
@DelecroixQuentin 

As of your use-case, from what I see in the code `ApiWrapper` only hides `RetriableException` and instead throws a new `UnreachableException` instead. That only covers responses with codes 0, 1xx and 5xx:

https://github.com/algolia/algoliasearch-client-php/blob/baa990fb0dd2ef2cad7978c1494227cb8c525fcb/src/RetryStrategy/ApiWrapper.php#L204-L212

Also, I am not sure, but I'd be very surprised to see that Algolia handles requests with invalid credentials by throwing a 500 and not 401. If that's the case then I'd better report _this_ to be a bug on Algolia API side. As it should be a 401, which wouldn't be hidden behind `UnreachableException`.

**Comment by DelecroixQuentin** [comment]
Hi @e1himself,

Ok I'm stupid, the code didn't catch the exception because of a `namespace` problem...
Sorry for the waste of time ...
