### ISSUE TITLE
Migration of the testing suite

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-php#639]
This is a ticket to list all the needed step to align the PHP client to our other clients regarding its testing system. I'm opening this issue to prepare a potential future OKR.

1. migrate the current integration tests to our Common Test Suite (CTS)
2. decide which PHP environments we want to continue to test against
3. migrate the credentials fetching for external contributors from the old API key generator to the new one
4. and finally, migrate to CircleCI

**Comment by chloelbn** [comment]
Done 💎
