### ISSUE TITLE
Tuber_Size

### ISSUE THREAD

**Issue by sofilibi** [algolia/algoliasearch-client-php#64]
Estimado Omar:

Los valores de tuber_size, según el manual van de 1 al 9. Quisera saber por qué cuando se han colocado valores de "0" (ceros), no se pintan las celdas....? o los valores se permiten desde cero.... ??. Adjunto una captura de pantalla. Gracias :) 

![image](https://cloud.githubusercontent.com/assets/4973956/13440108/75863b52-dfbe-11e5-92c7-3e0b52a142a7.png)

**Comment by rayrutjes** [comment]
@sofilibi we did not get your problem. We are closing this issue for now, would you mind re-opening an issue in english so we can dig into your problem?

**Comment by sofilibi** [comment]
Dear @rayrutjes , I'm really sorry, I guess I confused and I type this issue in another account, I apologyze for that, please sorry about that..

**Comment by rayrutjes** [comment]
No problem @sofilibi !
