### ISSUE TITLE
How to fix error "when enable agolia search then add product show error"

### ISSUE THREAD

**Issue by worldweb** [algolia/algoliasearch-client-php#645]
In laravel when create product without agolia search enable in product model then product created successfully, but when enable it it's show  error like "json_encode error: Recursion detected".

**Comment by chloelbn** [comment]
Hi @worldweb , sorry but I didn't understand your issue. Would you mind rephrasing it please? And add some reproducible code snippets and error messages so we can better understand what's going on.

Thanks and have a good day!

**Comment by damcou** [comment]
I'm closing this issue, feel free to re-open it if you have new information ;) .
