### ISSUE TITLE
Incompatiable for PHP 8.0?

### ISSUE THREAD

**Issue by CNSam** [algolia/algoliasearch-client-php#653]
- Algolia Client Version: 2.7.2
- Language Version: 8

### Description
Utilising PHP8.0 via Laravel Sail and during composer install I receive
> algolia/algoliasearch-client-php[2.7.0, ..., 2.7.2] require php ^5.3 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.

Any plans to support it soon?

### Steps To Reproduce
Use php 8.0 and pull in package from composer.

**Comment by greg0ire** [comment]
> Any plans to support it soon?

See https://github.com/algolia/algoliasearch-client-php/pull/644
