### ISSUE TITLE
PHP v8 support

### ISSUE THREAD

**Issue by sebastiansulinski** [algolia/algoliasearch-client-php#655]
Could you please add PHP v8 as an acceptable version - I run v8 locally and cannot update dependencies because of the existing constraint.

```
"require": {
        "php": "^5.3 || ^7.0 || ^8.0",
}
```

**Comment by ibrasho** [comment]
Check https://github.com/algolia/algoliasearch-client-php/pull/644.

You can try composer flag `--ignore-platform-reqs`.

**Comment by sebastiansulinski** [comment]
Is it not compatible with v8 though?

**Comment by davi5e** [comment]
The problem seems to be PHP 5 because this repo tries to maintain every PHP version concurrently, which appears to be getting exceedingly difficult to do.

**Comment by sebastiansulinski** [comment]
Perhaps worth dropping php 5 support - it's long past its eol?

**Comment by amoralesdesign** [comment]
Are they working on it?
 Problem 1
    - Root composer.json requires algolia/algoliasearch-client-php ^2.7.2 -> satisfiable by algolia/algoliasearch-client-php[2.7.2].
    - algolia/algoliasearch-client-php 2.7.2 requires php ^5.3 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by dellow** [comment]
Definitely PHP5 support needs to be dropped, that is crazy. Think this could be preventing a lot of projects from adopting PHP8 especially in the Laravel community.

**Comment by tao** [comment]
Yes, please add support. I'm also running into this same issue on a new Laravel project:

```
Error: Your lock file does not contain a compatible set of packages. Please run composer update.

Problem 1
    - algolia/algoliasearch-client-php is locked to version 2.7.2 and an update of this package was not requested.
    - algolia/algoliasearch-client-php 2.7.2 requires php ^5.3 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
```

Laravel supports PHP 8 by default now so I'm sure this problem will occur more for other users soon:

https://github.com/laravel/framework/blob/a253d0e40d3deb293d54df9f4455879af5365aab/composer.json#L18

**Comment by lukeify** [comment]
Add me in as another requester for PHP8 support. This is the final package in my dependencies list that is preventing me from running PHP8 (as of now, I'm using `--ignore-platform-reqs`).

**Comment by chloelbn** [comment]
This issue was fixed this https://github.com/algolia/algoliasearch-client-php/pull/656, I'm closing it!
