### ISSUE TITLE
TypeError: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by ImJustToNy** [algolia/algoliasearch-client-php#690]
- Algolia Client Version: 3.1.0
- Language Version: 8.0.11

### Description
When you try to use `RecommendedClilent()->getRelatedProducts()` it throws an error.
![image](https://user-images.githubusercontent.com/5730766/135988759-c29ecdb2-304a-43a9-90bb-069c1b1d199e.png)

### Steps To Reproduce
`RecommendClient::create('foo', 'bar', 'baz')->getRelatedProducts([
        'indexName' => 'example',
        'objectID' => '5'
    ])`

**Comment by DevinCodes** [comment]
Hi @ImJustToNy ,
Thank you for reporting this.

The parameter to `getRelatedProducts` should be an array of arrays, can you check with the following code, please?

```php
RecommendClient::create('foo', 'bar', 'baz')->getRelatedProducts([[ 'indexName' => 'example', 'objectID' => '5' ]]);
```

Thank you in advance!
