### ISSUE TITLE
PHP 8.1 AbstractResponse offset methods deprecation 

### ISSUE THREAD

**Issue by sebastiansulinski** [algolia/algoliasearch-client-php#694]
Under PHP 8.1 we're getting errors such as:

> Deprecated: Return type of Algolia\AlgoliaSearch\Response\AbstractResponse::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in

Fix is simple - just adding return types, but it would break backward compatibility - perhaps a candidate for the next major release?

**Comment by greg0ire** [comment]
> or the #[\ReturnTypeWillChange] attribute

**Comment by sebastiansulinski** [comment]
Yeah - or that - could you add and push?

**Comment by greg0ire** [comment]
I'm not a maintainer of this project, how about you open a PR?

**Comment by sebastiansulinski** [comment]
Oh sorry - thought you were :)
Let's see if any of the maintainers will pick it up, if not I'll have a look at it later - for now I'm just fetching it via fork to make it work with my project.

**Comment by damcou** [comment]
Hello @sebastiansulinski , thanks a lot for raising this issue, checking PHP8.1 compatibility is on my todo list. I'll should be on it this next or next week.

In the meantime, feel free to submit a PR with the `#[\ReturnTypeWillChange]` attribute , I'll have a look at it as well.

**Comment by sebastiansulinski** [comment]
Thanks @damcou appreciate it.
