### ISSUE TITLE
Consider adding static analysis

### ISSUE THREAD

**Issue by BackEndTea** [algolia/algoliasearch-client-php#709]
- Algolia Client Version: N/A
- Language Version: N/A

### Description

Consider using a static analysis tool (like PHPStan or Pslam), in order to catch basic errors, like the class not found issue introduced recently. 

Currently there is no way to verify that code that is not covered by tests isn't broken. With static analysis all code would be automatically type checked, which should make it (nearly) impossible for these kind of errors to happen.

It shouldn't be too much work to set it up with real low strictness, which should catch any basic errors. At a later point it could be configured to be more strict, catching more specific errors.

If you need any help with setting this up, i'd be more than happy to help.

**Comment by bodinsamuel** [comment]
Hello, thanks for the report.
It's unfortunate that those kind bug are appearing. However there is good news, we are in the process of releasing a new major that will have better testing overall ☺️ 

Code is there: https://github.com/algolia/algoliasearch-client-php/tree/next
Source is there: https://github.com/algolia/api-clients-automation

**Comment by BackEndTea** [comment]
Hey, thats great to see!

But even in a new major static analysis would still be beneficial to the overall quality of the project. 
Plus it would also help better document types towards the user.

Especially since this is a new major, and adding/changing types could be a BC break, this seems like the perfect time to add those.
