### ISSUE TITLE
`replaceAllObjects` + safe + new index = hangs forever

### ISSUE THREAD

**Issue by apfelbox** [algolia/algoliasearch-client-php#714]
- Algolia Client Version: 3.3.2
- Language Version: PHP 8.2

### Description
Using the method `replaceAllObjects` with a new index + safe hangs indefinitely:

```php
$index->replaceAllObjects($items, [
    "safe" => true,
]);
```

If you use this method with an index that not yet exists, it will just hang forever – possibly because the request to copy the config will never succeed.

### Steps To Reproduce
See above.

**Comment by samholguin** [comment]
We have the same.

**Comment by millotp** [comment]
Hello, in the new v4 version this is no longer an issue, please upgrade if you still encounter this.
