### ISSUE TITLE
Analytics API

### ISSUE THREAD

**Issue by b-roberts** [algolia/algoliasearch-client-php#715]
Could you add support for the analytics API? The AnalyticsClient is declared as Final so end users can't even extend the class to implement the additional endpoints themselves. 

See: 
https://github.com/algolia/algoliasearch-client-php/commit/90a562386d82afff841e094cec82806807b0269c

**Comment by millotp** [comment]
The analytics API is available in v4 ! https://www.algolia.com/doc/rest-api/analytics/
