### ISSUE TITLE
Can I switch off auto sync with Algolia temporary ?

### ISSUE THREAD

**Issue by PetroGromovo** [algolia/algoliasearch-client-php#727]
Working  with Algolia driver 
I got error 

`Impossible to connect, please check your Algolia Application Id.`

in in .env file algolia credentials are not found.

I wonder if there is a way to switch auto sync with Algolia server without run time errors in this 
case and without changing models code?

I do not see how that can be done, as Searchable trait is written in model...

Any decision ?

```
"laravel/framework": "^10.34.2",
"algolia/algoliasearch-client-php": "^3.4",

```
Thanks in advance!

**Comment by DevinCodes** [comment]
Hi @PetroGromovo ,

This seems to be a question surrounding Laravel, which is not part of this repository. To integrate Laravel and Algolia easily you can use the [Scout Extended](https://www.algolia.com/doc/framework-integration/laravel/getting-started/introduction-to-scout-extended/) package, which would also allow you to [turn off syncing with Algolia](https://www.algolia.com/doc/framework-integration/laravel/indexing/import-into-algolia/?client=php#pause-indexing).

Hope this helps, please reopen the issue if there's more context to this issue that's currently missing.

Cheers!
