### ISSUE TITLE
V4 how to check existings of a Index

### ISSUE THREAD

**Issue by alexander-schranz** [algolia/algoliasearch-client-php#732]
On v3 there was:

```php
$searchIndex = $client->initIndex($name);
$searchIndex->exists();
```

I could not find a existIndex method on v4 client version?

## Workaround

```php
try {
    $client->getSettings($indexName);
} catch (NotFoundException) {
    return false;
}

return true;
```

**Comment by millotp** [comment]
Hello, after hearing this feedback we decided to add this helper back, it will be available in the next version under `$searchClient->indexExists($name)`

**Comment by alexander-schranz** [comment]
@millotp thank you!
