### ISSUE TITLE
Laravel Scout:Import Fails with Algolia Client v4

### ISSUE THREAD

**Issue by Gautamsam3** [algolia/algoliasearch-client-php#733]
# Algolia Search client v4 not compatible with Laravel 11
According to Laravel's documentation, running the command **'_composer require algolia/algoliasearch-client-php_'** successfully installs version 4 of the Algolia Search client, which was released last week.

![algolia_v41](https://github.com/user-attachments/assets/457e344d-4c7f-4bbc-b0cf-f63238772a69)

-**Problem**: Despite the successful installation, running the command **'_php artisan scout:import "App\Models\Variant_"'** results in an error.

![algolia_v4](https://github.com/user-attachments/assets/515aaa3d-ed37-474b-ac77-ec1b00dbd4d5)

**Comment by alexander-schranz** [comment]
@Gautamsam3 the error is not algolia php package here. The error here is on laravel/scout they should define there required algolia SDK PHP version correctly currently they only support V3 and for V4 they need adopt the code.

Referencing here a block post about how to handle "optional" dependencies correctly: https://github.com/alexander-schranz/composer-optional-dependencies 

For you you can only require the supported verson currently via:

```
composer require algolia/algoliasearch-client-php:"^3.0"
```

**Comment by Gautamsam3** [comment]
Thank you @alexander-schranz 
Closing the issue -  reported the issue on [laravel/scout](https://github.com/laravel/scout/issues/855)
