### ISSUE TITLE
[bug]: php 8.3

### ISSUE THREAD

**Issue by MartkCz** [algolia/algoliasearch-client-php#736]
### Description

This file contains a fatal error https://github.com/algolia/algoliasearch-client-php/blob/main/lib/ApiException.php#L1

### Client

All

### Version

latest

### Relevant log output

```shell
PHP Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script
```

**Comment by millotp** [comment]
Thanks for the bug report, this will be fixed in the next release
