### ISSUE TITLE
Packagist license is "unlicense" despite LICENSE file being MIT

### ISSUE THREAD

**Issue by Pixelshaped** [algolia/algoliasearch-client-php#740]
Hi there,

Running the command `composer licenses` returns "unlicense" for this library.
![Screenshot from 2024-09-23 19-47-27](https://github.com/user-attachments/assets/c1903bb1-8a1e-43c4-b5c8-9f04bf75870a)

Not sure if that's a bug as the root LICENSE file seems to be MIT and correct otherwise.

v3 was MIT.

This might be a blocker for integrating in some projects.

**Comment by millotp** [comment]
Hey, thanks for reporting, this will be fixed in the next release
